application: map-idigi
version: github
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  MAP_WSDL_BASE: 'https://map.idigi.com/services/'
  MAJOR_VERSION: '1.0.0'
  MINOR_VERSION: 6


handlers:

- url: /static
  static_dir: static
  expiration: "60m"

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: .*
  script: main.app

